### ISSUE TITLE
how to regenerate the json?

### ISSUE THREAD

**Issue by mkinney** [jellehelsen/maas-api#1]
I like the idea of this lib.

How do you re-gen the maas-api.json file?

I'm not sure if I need to regenerate the json, or I have a different issue.

I tried doing a simple listing of the machines but got an error:

```
AttributeError: 'Handler' object has no attribute 'list'
```

Here's the code I used (other than replacing the xxx with the actual api key):
```
#!/usr/bin/env python3

API_KEY = "xxx"
MAAS_URL = "http://192.168.68.72:5240/MAAS/"

from maas_api import Client
client = Client(MAAS_URL, API_KEY)
for machine in client.machines.list():
    print(repr(machine))
```

When I use the python-libmaas library, I get a listing of my machines:

```
#!/usr/bin/env python3

API_KEY = "xxx"
MAAS_URL = "http://192.168.68.72:5240/MAAS/"

from maas.client import connect
client = connect(MAAS_URL, apikey=API_KEY)
for machine in client.machines.list():
    print(repr(machine))
```

**Comment by jellehelsen** [comment]
Archiving this project as I don't have the time to maintain and support this.
