### ISSUE TITLE
Please document more examples

### ISSUE THREAD

**Issue by greenmoss** [jellehelsen/maas-api#2]
This works as-is: `machines = client.machines.read()`

How do I pass command parameters? Here are some things I want to do, plus their command-line equivalent:
* Read a specific machine
    * `maas $MAAS_USER machines read hostname=my-maas-host`
* Create a network bond
    * `maas $MAAS_USER interfaces create-bond $MAAS_MACHINE name=$MAAS_BOND parents=$MAAS_PARENT1 mac_address=$MAAS_MAC1 parents=$MAAS_PARENT2 bond_mode=802.3ad bond_downdelay=0 bond_lacp_rate=fast bond_miimon=0 bond_num_grat_arp=1 bond_updelay=0 bond_xmit_hash_policy=layer2+3`
* Create a network bridge
    * `maas $MAAS_USER interfaces create-bridge $MAAS_MACHINE name=$MAAS_BR parent=$MAAS_PARENT1 bridge_type=ovs mac_address=$MAAS_MAC1 vlan=$MAAS_VLANID`

I've tried a few different `client.*` commands, but I get errors such as `TypeError: Action.__call__() takes 1 positional argument but 2 were given`

**Comment by jellehelsen** [comment]
Archiving this project as I don't have the time to maintain and support this.
